[package]
name = "mrkirdid/kirnet"
version = "3.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"Example",
	"Example/**",
	"kirnet-type-gen",
	"kirnet-type-gen/**",
	"src/ReplicatedStorage",
	"src/ReplicatedStorage/**",
	"src/_typesdump.luau",
	"aftman.toml",
	"default.project.json",
	"selene.toml",
	".stylua.toml",
]

[dependencies]
Promise = "evaera/promise@4.0.0"
