import { ServiceDef } from "./parser";

/**
 * Generate the Types.luau content from parsed service definitions.
 *
 * The output is a **drop-in replacement** for KirNet.  Users swap their
 * require path and keep calling `KirNet.GetService("Name")` as normal -
 * Luau intersection-type overloads on GetService narrow the return type
 * to the correct service type based on the string literal argument.
 */
export function generateTypesContent(
	services: ServiceDef[],
	requirePath: string,
): string {
	const sorted = [...services].sort((a, b) => a.name.localeCompare(b.name));

	const lines: string[] = [];

	lines.push("-- AUTO-GENERATED by KirNet Type Generator");
	lines.push("-- Do not edit manually. This file is overwritten on every save.");
	lines.push("--");
	lines.push("-- Require this module instead of KirNet for fully typed GetService().");
	lines.push("-- All other KirNet methods (CreateServerSignal, RegisterService, etc.) work as normal.");
	lines.push("");
	lines.push(`local KirNet = require(${requirePath})`);
	lines.push("");

	if (sorted.length === 0) {
		lines.push("return KirNet");
		return lines.join("\n") + "\n";
	}

	// -- Inlined KirNet types so luau-lsp resolves them without require-path resolution
	lines.push("-- ============================================================");
	lines.push("-- KirNet types (inlined for reliable autocomplete)");
	lines.push("-- ============================================================");
	lines.push("");
	lines.push("type ServerSignal<T...> = {");
	lines.push("\tFire: (self: ServerSignal<T...>, player: Player, T...) -> (),");
	lines.push("\tFireAll: (self: ServerSignal<T...>, T...) -> (),");
	lines.push("\tFireExcept: (self: ServerSignal<T...>, player: Player, T...) -> (),");
	lines.push("\tFireList: (self: ServerSignal<T...>, players: { Player }, T...) -> (),");
	lines.push("\tConnect: (self: ServerSignal<T...>, callback: (T...) -> ()) -> (),");
	lines.push("\tOnce: (self: ServerSignal<T...>, callback: (T...) -> ()) -> (),");
	lines.push("\tWait: (self: ServerSignal<T...>, timeout: number?) -> T...,");
	lines.push("\tDisconnect: (self: ServerSignal<T...>) -> (),");
	lines.push("}");
	lines.push("");
	lines.push("type ClientSignal<T...> = {");
	lines.push("\tFireServer: (self: ClientSignal<T...>, T...) -> (),");
	lines.push("\tOnServerEvent: (self: ClientSignal<T...>, callback: (player: Player, T...) -> ()) -> (),");
	lines.push("}");
	lines.push("");
	lines.push("type Signal<T...> = {");
	lines.push("\tFire: (self: Signal<T...>, player: Player, T...) -> (),");
	lines.push("\tFireAll: (self: Signal<T...>, T...) -> (),");
	lines.push("\tFireExcept: (self: Signal<T...>, player: Player, T...) -> (),");
	lines.push("\tFireList: (self: Signal<T...>, players: { Player }, T...) -> (),");
	lines.push("\tFireServer: (self: Signal<T...>, T...) -> (),");
	lines.push("\tConnect: (self: Signal<T...>, callback: (T...) -> ()) -> (),");
	lines.push("\tOnce: (self: Signal<T...>, callback: (T...) -> ()) -> (),");
	lines.push("\tWait: (self: Signal<T...>, timeout: number?) -> T...,");
	lines.push("\tDisconnect: (self: Signal<T...>) -> (),");
	lines.push("\tOnServerEvent: (self: Signal<T...>, callback: (player: Player, T...) -> ()) -> (),");
	lines.push("}");
	lines.push("");
	lines.push("type ServerFunction<TReturn> = {");
	lines.push("\tCall: (self: ServerFunction<TReturn>, ...any) -> TReturn,");
	lines.push("}");
	lines.push("");

	// -- Service Types section
	lines.push("-- ============================================================");
	lines.push("-- Service Types");
	lines.push("-- ============================================================");
	lines.push("");

	for (const svc of sorted) {
		const typeName = `${svc.name}Type`;
		lines.push(`export type ${typeName} = {`);
		for (const field of svc.fields) {
			// Strip any leftover KirNet. prefix - generated file defines types locally
			const fieldType = field.type
				.replace(/\bKirNet\s*\.\s*ServerSignal\s*</g, "ServerSignal<")
				.replace(/\bKirNet\s*\.\s*ClientSignal\s*</g, "ClientSignal<")
				.replace(/\bKirNet\s*\.\s*ServerFunction\s*</g, "ServerFunction<")
				.replace(/\bKirNet\s*\.\s*Signal\s*</g, "Signal<")
				.replace(/\bKirNet\s*\.\s*Function\s*</g, "ServerFunction<");
			lines.push(`\t${field.name}: ${fieldType},`);
		}
		lines.push("}");
		lines.push("");
	}

	// -- Typed KirNet with GetService overloads
	lines.push("-- ============================================================");
	lines.push("-- Typed KirNet - drop-in replacement with overloaded GetService");
	lines.push("-- ============================================================");
	lines.push("");

	lines.push("type GetServiceOverloads =");
	for (let i = 0; i < sorted.length; i++) {
		const svc = sorted[i];
		const prefix = i === 0 ? "\t" : "\t& ";
		lines.push(`${prefix}((name: "${svc.name}") -> ${svc.name}Type)`);
	}
	const svcFallbackPrefix = sorted.length === 0 ? "\t" : "\t& ";
	lines.push(`${svcFallbackPrefix}((name: string) -> { [string]: any })`);
	lines.push("");

	lines.push("type RegisterServiceOverloads =");
	for (let i = 0; i < sorted.length; i++) {
		const svc = sorted[i];
		const prefix = i === 0 ? "\t" : "\t& ";
		lines.push(`${prefix}((name: "${svc.name}", definition: ${svc.name}Type) -> ${svc.name}Type)`);
	}
	const regFallbackPrefix = sorted.length === 0 ? "\t" : "\t& ";
	lines.push(`${regFallbackPrefix}((name: string, definition: { [string]: any }) -> { [string]: any })`);
	lines.push("");

	lines.push("type TypedKirNet = {");
	lines.push("\tGetService: GetServiceOverloads,");
	lines.push("\tRegisterService: RegisterServiceOverloads,");
	lines.push("\tCreateServerSignal: typeof(KirNet.CreateServerSignal),");
	lines.push("\tCreateClientSignal: typeof(KirNet.CreateClientSignal),");
	lines.push("\tCreateSignal: typeof(KirNet.CreateSignal),");
	lines.push("\tCreateServerFunction: typeof(KirNet.CreateServerFunction),");
	lines.push("\tCreateFunction: typeof(KirNet.CreateFunction),");
	lines.push("\tUseMiddleware: typeof(KirNet.UseMiddleware),");
	lines.push("\tSetDebug: typeof(KirNet.SetDebug),");
	lines.push("}");
	lines.push("");
	lines.push("return (KirNet :: any) :: TypedKirNet");

	return lines.join("\n") + "\n";
}